version: '3'
services:
  nwabap752:
    image: nwabap:7.52
    container_name: nwabap752
    hostname: vhcalnplci
    ports:
      - "8000:8000"
      - "44300:44300"
      - "3300:3300"
      - "3200:3200"
    stdin_open: true
    tty: true
    command: /bin/bash
